accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create_user$', views.CreateUser.as_view(), name="create_user"),
    url(r'^login', views.login_user, name="login"),
    url(r'^logout$', views.logout_user, name="logout"),
    url(r'^profile/(?P<username>.*)$', views.get_profile, name="get_profile"),
    url(r'^change_password$', views.change_password, name="change_password")
]

articles/urls.py
from django.conf.urls import url
from . import views
from . import ajax

urlpatterns = [
    url(r'^create_article$', views.create_article, name="create_article"),
    url(r'^$', views.get_articles, name="get_articles"),
    url(r'^(?P<page>\d+)', views.get_articles, name="get_articles"),
    url(r'^article/(?P<slug>[\w-]+)$', views.get_article, name="get_article"),
    url(r'^update/(?P<slug>[\w-]+)$', views.UpdateArticle.as_view(), name="update_article"),
    url(r'^delete/(?P<id>\d+)$', views.delete_article, name="delete_article"),
    url(r'^vote_article/(?P<id_article>\d+)', ajax.vote_article, name="vote_article"),
    url(r'^vote_comment/(?P<id_comment>\d+)', ajax.vote_comment, name="vote_comment"),
]

articles/models.py
from django.core.validators import MaxLengthValidator
from django.db import models
from django.contrib.auth.models import User
from articles.utils import unique_slugify


class Article(models.Model):
    """
    Classe qui représente un article
    Chaque article est lié à un utilisateur qui en est l'auteur
    """
    title = models.CharField(max_length=200, verbose_name="Titre")
    slug = models.SlugField(unique=True, max_length=100, verbose_name="Slug")
    intro = models.TextField(verbose_name="Introduction")
    content = models.TextField(verbose_name="Contenu")
    author = models.ForeignKey(User, verbose_name="Auteur")
    date = models.DateTimeField(auto_now_add=True, verbose_name="Date de création")
    last_updated = models.DateTimeField(auto_now=True, verbose_name="Dernière modification")
    views = models.IntegerField(default=0, verbose_name="Nombre de vues")
    likes = models.IntegerField(default=0, verbose_name="Nombre de likes")
    dislikes = models.IntegerField(default=0, verbose_name="Nombre de dislikes")
    score = models.IntegerField(default=0, verbose_name="Score")
    likes_width = models.IntegerField(default=0)
    dislikes_width = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        unique_slugify(self, self.title)
        self.score = self.likes - self.dislikes
        if self.likes + self.dislikes > 0:
            self.likes_width = (self.likes / (self.likes + self.dislikes)) * 100
            self.dislikes_width = (self.dislikes / (self.likes + self.dislikes)) * 100
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return "article : %s" % self.title


class Commentaire(models.Model):
    """
    Classe qui représente les commentaires d'un article
    Chaque commentaire est lié à un article et à un utilisateur
    """
    content = models.TextField(verbose_name="Contenu", validators=[MaxLengthValidator(500)])
    author = models.CharField(max_length=50, verbose_name="Auteur")
    likes = models.IntegerField(default=0, verbose_name="Nombre de likes")
    dislikes = models.IntegerField(default=0, verbose_name="Nombre de dislikes")
    score = models.IntegerField(default=0, verbose_name="Score")
    date = models.DateTimeField(auto_now_add=True, verbose_name="Date")
    article = models.ForeignKey(Article, verbose_name="Article")

    def save(self, *args, **kwargs):
        self.score = self.likes - self.dislikes
        super(Commentaire, self).save(*args, **kwargs)

    def __str__(self):
        return "commentaire : %s" % self.content

articles/forms.py
from django import forms
from articles.models import Article, Commentaire
from django.contrib.auth.models import User
from articles.utils import bleach_html


class CreateArticleForm(forms.ModelForm):
    title = forms.CharField(error_messages={'required': "Votre titre est vide"})
    intro = forms.CharField(error_messages={'required': "Votre intro est vide"})
    content = forms.CharField(error_messages={'required': "Votre article est vide"})

    def clean_title(self):
        return bleach_html(self.cleaned_data.get('title'))

    def clean_intro(self):
        return bleach_html(self.cleaned_data.get('intro'))

    def clean_content(self):
        return bleach_html(self.cleaned_data.get('content'))

    class Meta:
        model = Article
        fields = ["title", "intro", "content"]


class CreateCommentForm(forms.Form):
    author = forms.CharField(widget=forms.TextInput, required=False, label="Pseudo")
    content = forms.CharField(widget=forms.Textarea, label="Commentaire", error_messages={'required': "Votre commentaire est vide"})

    # permet de récupérer l'objet request
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CreateCommentForm, self).__init__(*args, **kwargs)

    def clean_content(self):
        return bleach_html(self.cleaned_data.get('content'))

    def clean_author(self):
        author = self.cleaned_data.get('author')
        if User.objects.filter(username=author).exists():
            raise forms.ValidationError("Pseudo déjà utilisé par un membre du site")
        if author == "":
            author = "Anonyme"
        return bleach_html(author)

articles/views.py
import json
import os
from datetime import datetime, timedelta
import collections

from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import user_passes_test
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404
from django.views.generic.edit import UpdateView
from django.core.paginator import Paginator, EmptyPage
from django.contrib import messages

from articles.models import Article, Commentaire
from articles.forms import CreateArticleForm, CreateCommentForm
from articles.utils import bleach_html


@user_passes_test(lambda u: u.has_perm('articles.add_article'))
def create_article(request):
    """
    Création d'un article

    Il faut être connecté et avoir les bons droits
    """
    user = request.user

    if request.method == 'POST':
        form = CreateArticleForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            intro = form.cleaned_data['intro']
            content = form.cleaned_data['content']

            # sauvegarde de l'article
            article = Article(title=title, intro=intro, content=content, author=user)
            article.save()

            # on redirige vers l'article créé
            return redirect("get_article", slug=article.slug)

    else:
        form = CreateArticleForm()

    return render(request, "articles/create_article.html", locals())


class UpdateArticle(UpdateView):
    """
    Modification d'un article

    L'utilisateur qui veut modifier l'article doit en être l'auteur
    """
    model = Article
    fields = ['title', 'intro', 'content']
    template_name = "articles/update_article.html"

    # on vérifie que l'user connecté est bien l'auteur de l'article
    def dispatch(self, request, *args, **kwargs):
        if request.user != self.get_object().author and not request.user.is_staff:
            raise PermissionDenied()
        return super(UpdateArticle, self).dispatch(request, *args, **kwargs)

    # récupération du bon article selon le slug
    def get_object(self):
        article = Article.objects.get(slug=self.kwargs['slug'])
        article.content = bleach_html(article.content)
        article.content = article.content.replace('"', '\\"')
        print(article.content)
        return article

    # on redirige vers l'article modifié en cas de succès
    def get_success_url(self):
        messages.success(self.request, 'Article modifié !', extra_tags='done')
        return reverse_lazy("get_article", kwargs={'slug': self.object.slug})


def delete_article(request, id):
    """
    Suppression d'un article selon un id
    """
    article = get_object_or_404(Article, pk=id)
    user = request.user

    # on vérifie que l'utilisateur a les bons droits
    # et qu'il est l'auteur de l'article
    if not user.is_staff or user != article.author:
        raise PermissionDenied()

    # suppression de l'article
    article.delete()

    return redirect("get_articles")


# class GetArticlesList(ListView):
#     """
#     Récupération des articles par page
#     10 articles par page
#     """
#     model = Article
#     template_name = "articles/articles_list.html"
#     context_object_name = "articles"
#     paginate_by = 10
#     # page name : page_obj
#
#     def get_queryset(self):
#         order = self.request.GET.get('order', '-date')
#         print(order)
#         if order != "-date" and order != "-views" and order != "-score":
#             order = "-date"
#         print(order)
#         return Article.objects.order_by(order)


def get_articles(request, page=1):
    """
    Récupération des articles par page
    10 articles par page
    """
    # récupération du filtre
    order = request.GET.get('order', '-date')
    if order != "-date" and order != "-views" and order != "-score":
        order = "-date"

    articles_list = Article.objects.order_by(order)
    paginator = Paginator(articles_list, 10)

    try:
        articles = paginator.page(page)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    # récupération classement ligue 1
    f1 = os.path.join(os.path.dirname(__file__), 'json/ranking_ligue1.json')
    ranking = json.load(open(f1), object_pairs_hook=collections.OrderedDict)

    # récupération du dernier résultat et du prochain match de Rennes
    f2 = os.path.join(os.path.dirname(__file__), 'json/last_next_match.json')
    last_next_match = json.load(open(f2))

    last_result = last_next_match['last_result']
    last_result['date'] = datetime.strptime(last_result['date'], "%Y-%m-%dT%H:%M:%SZ") + timedelta(hours=1)
    next_match = last_next_match['next_match']
    next_match['date'] = datetime.strptime(next_match['date'], "%Y-%m-%dT%H:%M:%SZ") + timedelta(hours=1)

    return render(request, "articles/articles_list.html", locals())


def get_article(request, slug):
    """
    Récupération d'un article selon un slug

    Le nombre de vues est augmenté à chaque fois qu'un
    utilisateur accède la première fois à l'article

    Lors de cette première visite un cookie est placé
    Le cookie est une liste qui correspond aux id des articles
    que l'utilisateur a vu
    """
    article = get_object_or_404(Article, slug=slug)
    # derniers articles pour les afficher
    last_articles = Article.objects.all().exclude(slug=article.slug).order_by('-date')[:5]
    # variables utiles pour le vote
    votes_article = {}
    already_voted = False
    id_article_texte = str(article.id)
    form_success = False

    # récupération des commentaires de l'article
    # 10 par page
    comments_list = Commentaire.objects.filter(article=article).order_by('-date')
    paginator = Paginator(comments_list, 10)

    page_comments = request.GET.get('page_comments', '1')
    int(page_comments)

    try:
        comments = paginator.page(page_comments)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    # on test si l'utilisateur a déjà voté pour l'article
    # afin de masqué un des boutons de vote si c'est le cas
    user = request.user
    if user.is_authenticated():
        votes_article = user.profile.votes_articles
    else:
        if 'cookie_votes_article' in request.session:
            votes_article = request.session['cookie_votes_article']

    if id_article_texte in votes_article:
        opinion = votes_article[id_article_texte]
        already_voted = True

    # vérifie si l'utilisateur a déjà vu l'article
    # fonction annexe
    set_cookie_view_article(request, article)

    # traitement du formulaire de commentaire
    # fonction annexe
    response = create_comment_form(request, article)
    if response['send']:
        if response['saved']:
            messages.success(request, 'Commentaire posté !', extra_tags='done')
            return redirect("get_article", article.slug)
        else:
            form = response['form']
            messages.error(request, 'Erreur dans le formulaire', extra_tags='report_problem')

    return render(request, "articles/article.html", locals())


def set_cookie_view_article(request, article):
    """
    Fonction annexe permettant de tester
    le cookie pour les vues d'un article
    """
    views_article = []
    user = request.user

    # si l'utilisateur est connecté, on regarde s'il a deja vu l'article
    if user.is_authenticated():
        views_article = user.profile.views_articles
        if article.id not in views_article:
            article.views += 1
            article.save()
            views_article.append(article.id)
            user.profile.views_articles = views_article
            user.profile.save()

    else:
        # on test si l'utilisateur avait déjà vu cet article
        if 'cookie_views_article' in request.session:
            views_article = request.session['cookie_views_article']
            # si l'utilisateur n'avait pas vu cet article
            if article.id not in views_article:
                article.views += 1
                article.save()
                views_article.append(article.id)
        else:
            article.views += 1
            article.save()
            views_article.append(article.id)

        # on met à jour le cookie
        request.session['cookie_views_article'] = views_article


def create_comment_form(request, article):
    """
    Fonction annexe qui gère le post de commentaire

    L'utilisateur doit entrer un pseudo s'il n'est pas connecté
    """
    user = request.user
    result = {}

    if request.method == 'POST':
        form = CreateCommentForm(request.POST, request=request)
        result['send'] = True

        if form.is_valid():
            author = form.cleaned_data['author']
            content = form.cleaned_data['content']

            if user.is_authenticated():
                author = user.username

            # sauvegarde du commentaire
            commentaire = Commentaire(content=content, author=author, article=article)
            commentaire.save()

            result['saved'] = True
        else:
            result['saved'] = False

    else:
        form = CreateCommentForm(request=request)
        result['send'] = False

    result['form'] = form

    return result

articles/templates/articles/article.html
{% extends "base.html" %}

{% load static %}
{% load bleach_tags %}
{% load l10n %}

{% block css %}
    <link rel="stylesheet/less" type="text/css" href="{% static 'articles/css/style-articles.less' %}">
{% endblock %}

{% block js_url %}
    <script src="{% static 'js/dotdot.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
{# ------- #}
{# article #}
{# ------- #}
<div class="mdl-grid" id="article_detail" >
    <div class="mdl-cell mdl-cell--10-col">
        {# partie du haut #}
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--9-col">
                <p id="article_date">{{ article.date | date:"j F Y" }}</p>
                <h1>{{ article.title }}</h1>
                <p id="article_author"><i>Écrit par</i> <a href=""><b>{{ article.author.username }}</b></a></p>
            </div>

            {#  article likes #}
            <div class="mdl-cell mdl-cell--3-col mdl-cell--12-col-tablet mdl-cell--12-col-phone" id="article_likes_parent">
                <div id="article_likes">
                    <p id="nb_vues">
                        vues<br>
                        <span>{{ article.views }}</span>
                    </p>
                    <div id="div_bar_votes">
                        {% if article.likes_width == 0 and article.dislikes_width == 0 %}
                            <div class="bar_votes" style="width: 100%; background: #727272"></div>
                        {% else %}
                            <div class="bar_votes" id="bar_likes" style="width: {{ article.likes_width }}%;"></div>
                            <div class="bar_votes" id="bar_dislikes" style="width: {{ article.dislikes_width }}%;"></div>
                        {% endif %}
                    </div>
                    <div id="div_nb_vote">

                        <span class="nb_vote" id="icon_article_likes"><i class="material-icons">thumb_up</i> {{ article.likes }}</span>
                        <span class="nb_vote" id="icon_article_dislikes"><i class="material-icons">thumb_down</i> {{ article.dislikes }}</span>

                    </div>
                </div>
            </div>
            {# fin article likes #}
        </div>
        {# fin partie du haut #}

        {# parti du bas #}
        <div id="article_intro">{{ article.intro|safe }}</div>

        <div id="article_content">{{ article.content|bleach }}</div>

    </div>
</div>

{# ------------------------ #}
{# bandeau votes et partage #}
{# ------------------------ #}
<div id="div_buttons_vote">
    <div class="mdl-grid" id="div_buttons_vote_content">
        <div class="mdl-cell--10-col">
            {% if already_voted %}

                {% if opinion == "like_article" %}
                        <a href="javascript:void(0);" id="like_article" class="vote_article already_voted">
                            <p>
                                <i class="material-icons">thumb_up</i>
                                <span>Cool</span>
                            </p>
                        </a>
                        <a href="javascript:void(0);" id="dislike_article" class="vote_article no_voted_yet">
                            <p>
                                <i class="material-icons">thumb_down</i>
                                <span>Nul</span>
                            </p>
                        </a>

                {% elif opinion == "dislike_article" %}
                        <a href="javascript:void(0);" id="like_article" class="vote_article no_voted_yet">
                            <p>
                                <i class="material-icons">thumb_up</i>
                                <span>Cool</span>
                            </p>
                        </a>
                        <a href="javascript:void(0);" id="dislike_article" class="vote_article already_voted">
                            <p>
                                <i class="material-icons">thumb_down</i>
                                <span>Nul</span>
                            </p>
                        </a>
                {% endif %}

                {% else %}
                        <a href="javascript:void(0);" id="like_article" class="vote_article">
                            <p>
                                <i class="material-icons">thumb_up</i>
                                <span>Cool</span>
                            </p>
                        </a>
                        <a href="javascript:void(0);" id="dislike_article" class="vote_article">
                            <p>
                                <i class="material-icons">thumb_down</i>
                                <span>Nul</span>
                            </p>
                        </a>
                {% endif %}

                        {% comment %}
                        <a href="javascript:void(0);" id="share_article" class="vote_article">
                            <p>
                                <i class="material-icons">share</i>
                                <span>Partager</span>
                            </p>
                        </a>
                        {% endcomment %}

        </div>
    </div>
</div>

    {# bouton modification article #}
    {% if perms.articles.change_article and request.user == article.author or request.user.is_staff %}

        {% block fab_create_article %}
        {% endblock %}

            <a href="{% url "update_article" article.slug %}" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect button_fab_action" id="button_edit_article">
                <i class="material-icons">mode_edit</i>
            </a>

            <div class="mdl-tooltip mdl-tooltip--large mdl-tooltip--left" for="button_edit_article">
                Modifier cet article
            </div>
    {% endif %}

{# --------------------------------- #}
{# commentaires et derniers articles #}
{# --------------------------------- #}
<div class="mdl-grid" id="article_comments_suggest" >
    <div class="mdl-cell mdl-cell--1-col"></div>
    <div class="mdl-cell mdl-cell--6-col" id="article_comments">
        <h4>Commentaires</h4>
        <div id="article_comments_head">
            {% include "articles/create_comment.html" %}
        </div>

        <div id="article_comments_body">
            {% include "articles/article_comments.html" %}
        </div>

    </div>

    <div class="mdl-cell mdl-cell--4-col mdl-cell--6-col-tablet" id="last_articles">
        <h4>Derniers articles</h4>
        {% for last_article in  last_articles %}
            <a href="{% url "get_article" last_article.slug %}">
                <div class="last_article_card">
                    <p class="last_article_title">{{ last_article.title }}</p>
                    <p class="last_article_date">{{ last_article.date | date:"d b"}}</p>
                    <p class="last_article_views">{{ last_article.views }} <em>vues</em></p>
                </div>
            </a>
        {% endfor %}
    </div>
    <div class="mdl-cell mdl-cell--1-col"></div>
</div>

{% endblock %}


{# --------- #}
{# Script JS #}
{# --------- #}
{% block script %}
<script>
    // ajax - vote_article
    $("#div_buttons_vote").on('click', "a.vote_article", function() {
        $.ajax({
            url: "{% url "vote_article" article.id %}?opinion=" + $(this).attr("id"),
            type: 'get',
            dataType: "json",
            success: function(data) {
                $("#div_buttons_vote").load("{% url "get_article" article.slug %} #div_buttons_vote_content");
                $("#article_likes_parent").load("{% url "get_article" article.slug %} #article_likes");
            },
            failure: function(data) {
                console.log('Erreur', data);
            }
        })
    });

    // ajax - vote_comment
    $("#article_comments_suggest").on('click', "a.vote_comment", function() {
        var id_commentaire = $(this).attr("data-id-comment");
        var like = $(this).attr("id");
        // mettre bon id commentaire dans l'url
        var url = "{% url "vote_comment" 999 %}".replace("999", id_commentaire);

        $.ajax({
            url: url + "?opinion=" + like,
            type: 'get',
            dataType: "json",
            success: function(data) {
                var page = $("#article_comments_pagination .current b").text();
                $("#parent_comment_" + id_commentaire ).load("{% url "get_article" article.slug %}?page_comments=" + page + " #comment_" + id_commentaire)
            },
            failure: function(data) {
                console.log('Erreur', data);
            }
        })
    });

    // ajax - page_comments
    $("#article_comments_suggest").on('click', "a.comments_page", function() {
        var page = $(this).attr("id");

        $("#article_comments_body").load("{% url "get_article" article.slug %}?page_comments=" + page + " #article_comments_body_content")

    });

    // margin-left for last_articles on samll devices
    $(function(){
        if (window.matchMedia("(max-width: 839px)").matches && window.matchMedia("(min-width: 480px)").matches) {
            var width = $('.mdl-cell--1-col').width() - 16;
            console.log(width)
            $('#last_articles').css('margin-left', width + 'px');
        }
    });

    // truncat last_article_title
    $(document).ready(function() {
        $(".last_article_title").dotdotdot({
            wrap: 'letter'
        });
    });
</script>
{% endblock %}

articles/templates/articles/create_article.html
{% extends "articles/form_create_update_article.html" %}

{% block page_title %}
    Ajouter un article
{% endblock %}

{% block form_input %}Ajouter l'article{% endblock %}


{% block script %}
    <script>
        $('#id_content').trumbowyg({
            lang: 'fr',
            btnsDef: {
                // Customizables dropdowns
                formattingLight: {
                    dropdown: ['h1', 'p', 'blockquote'],
                    ico: 'formatting' // Apply formatting icon
                }
            },
            btns: [
                'formattingLight',
                '|', 'bold', 'italic', 'underline', 'strikethrough',
                '|', 'link',
                '|', 'insertImage',
                '|', 'btnGrp-lists'
            ],
            fullscreenable: false,
            autogrow: true,
            removeformatPasted: true
        });

        $('.trumbowyg-editor').attr('style', 'height: 100%');
    </script>
{% endblock %}

articles/templates/articles/create_comment.html
<form action="" method="post">
    {% csrf_token %}

    {% if not request.user.is_authenticated %}
      {% if form.author.errors %}
          {% for error in form.author.errors %}
              <p class="form_errors"><i class="material-icons">report_problem</i> {{ error }}</p>
          {% endfor %}
      {% endif %}
      <div class="mdl-textfield mdl-js-textfield mdl-textfield-block">
        <input class="mdl-textfield__input" type="text" name="author" id="id_author">
        <label class="mdl-textfield__label" for="id_author">Pseudo</label>
      </div>
    {% endif %}
      {% if form.content.errors %}
          {% for error in form.content.errors %}
              <p class="form_errors"><i class="material-icons">report_problem</i> {{ error }}</p>
          {% endfor %}
      {% endif %}
      <div class="mdl-textfield mdl-js-textfield">
        <textarea class="mdl-textfield__input" type="text" name="content" rows= "3" id="id_content" ></textarea>
        <label class="mdl-textfield__label" for="id_content">Votre commentaire</label>
      </div>
    <input type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect" value="Valider">
</form>

articles/templates/articles/form_create_update_article.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'editor/dist/ui/trumbowyg.min.css' %}">
    <link rel="stylesheet/less" type="text/css" href="{% static 'articles/css/style-articles.less' %}">
    <link rel="stylesheet/less" type="text/css" href="{% static 'css/style-form.less' %}">
{% endblock %}

{% block js_url %}
    <script src="{% static 'editor/dist/trumbowyg.min.js' %}"></script>
{% endblock %}

{% block content %}

<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--10-col">
        <h2 class="page_title">{% block page_title %}{% endblock %}</h2>

        <div class="mdl-grid">
            <div id="div_form_create_update_article">

                <form action="" method="post">
                    {% csrf_token %}

                      {% if form.title.errors %}
                          {% for error in form.title.errors %}
                              <p class="form_errors"><i class="material-icons">report_problem</i> {{ error }}</p>
                          {% endfor %}
                      {% endif %}

                      <div class="input">
                          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" id="id_title" maxlength="200" name="title" type="text" value="{% block value_title %}{% endblock %}">
                            <label class="mdl-textfield__label" for="id_title">Titre de l'article</label>
                          </div>
                      </div>

                      {% if form.intro.errors %}
                          {% for error in form.intro.errors %}
                              <p class="form_errors"><i class="material-icons">report_problem</i> {{ error }}</p>
                          {% endfor %}
                      {% endif %}

                      <div class="input">
                          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <textarea class="mdl-textfield__input" id="id_intro" name="intro" rows="4" cols="50">{% block value_intro %}{% endblock %}</textarea>
                            <label class="mdl-textfield__label" for="id_intro">Introduction de l'article</label>
                          </div>
                      </div>

                      {% if form.content.errors %}
                          {% for error in form.content.errors %}
                              <p class="form_errors"><i class="material-icons">report_problem</i> {{ error }}</p>
                          {% endfor %}
                      {% endif %}

                      <div class="input">
                          <textarea id="id_content" name="content"></textarea>
                      </div>

                    <input type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect" value="{% block form_input %}{% endblock %}">
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block snackbar %}
    {% if form.errors %}
    <div class="snackbar" id="form_state">
        <span class="snackbar_text"><i class="material-icons">report_problem</i> {% block error_form_snackbar %}Erreur dans le formulaire{% endblock %}</span>
        <span class="snackbar_close">Fermer</span>
    </div>
    {% endif %}
{% endblock %}

{% block fab_create_article %}{% endblock %}

articles/templates/articles/update_article.html
{% extends "articles/form_create_update_article.html" %}
{% load bleach_tags %}

{% block page_title %}Modifier un article{% endblock %}

{% block form_input %}Modifier l'article{% endblock %}

{% block value_title %}{{ object.title }}{% endblock %}

{% block value_intro %}{{ object.intro }}{% endblock %}


{% block script %}
    <script>
        $('#id_content').trumbowyg({
            lang: 'fr',
            btnsDef: {
                // Customizables dropdowns
                formattingLight: {
                    dropdown: ['h1', 'p', 'blockquote'],
                    ico: 'formatting' // Apply formatting icon
                }
            },
            btns: [
                'formattingLight',
                '|', 'bold', 'italic', 'underline', 'strikethrough',
                '|', 'link',
                '|', 'insertImage',
                '|', 'btnGrp-lists'
            ],
            fullscreenable: false,
            autogrow: true,
            removeformatPasted: true
        });

        var content = "{{ object.content | safe }}";

        $('#id_content').trumbowyg('html', content);

        $('.trumbowyg-editor').attr('style', 'height: 100%');
    </script>
{% endblock %}