accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create_user$', views.CreateUser.as_view(), name="create_user"),
    url(r'^login', views.login_user, name="login"),
    url(r'^logout$', views.logout_user, name="logout"),
    url(r'^profile/(?P<username>.*)$', views.get_profile, name="get_profile"),
    url(r'^change_password$', views.change_password, name="change_password")
]

articles/models.py
from django.core.validators import MaxLengthValidator
from django.db import models
from django.contrib.auth.models import User
from articles.utils import unique_slugify


class Article(models.Model):
    """
    Classe qui représente un article
    Chaque article est lié à un utilisateur qui en est l'auteur
    """
    title = models.CharField(max_length=200, verbose_name="Titre")
    slug = models.SlugField(unique=True, max_length=100, verbose_name="Slug")
    intro = models.TextField(verbose_name="Introduction")
    content = models.TextField(verbose_name="Contenu")
    author = models.ForeignKey(User, verbose_name="Auteur")
    date = models.DateTimeField(auto_now_add=True, verbose_name="Date de création")
    last_updated = models.DateTimeField(auto_now=True, verbose_name="Dernière modification")
    views = models.IntegerField(default=0, verbose_name="Nombre de vues")
    likes = models.IntegerField(default=0, verbose_name="Nombre de likes")
    dislikes = models.IntegerField(default=0, verbose_name="Nombre de dislikes")
    score = models.IntegerField(default=0, verbose_name="Score")
    likes_width = models.IntegerField(default=0)
    dislikes_width = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        unique_slugify(self, self.title)
        self.score = self.likes - self.dislikes
        if self.likes + self.dislikes > 0:
            self.likes_width = (self.likes / (self.likes + self.dislikes)) * 100
            self.dislikes_width = (self.dislikes / (self.likes + self.dislikes)) * 100
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return "article : %s" % self.title


class Commentaire(models.Model):
    """
    Classe qui représente les commentaires d'un article
    Chaque commentaire est lié à un article et à un utilisateur
    """
    content = models.TextField(verbose_name="Contenu", validators=[MaxLengthValidator(500)])
    author = models.CharField(max_length=50, verbose_name="Auteur")
    likes = models.IntegerField(default=0, verbose_name="Nombre de likes")
    dislikes = models.IntegerField(default=0, verbose_name="Nombre de dislikes")
    score = models.IntegerField(default=0, verbose_name="Score")
    date = models.DateTimeField(auto_now_add=True, verbose_name="Date")
    article = models.ForeignKey(Article, verbose_name="Article")

    def save(self, *args, **kwargs):
        self.score = self.likes - self.dislikes
        super(Commentaire, self).save(*args, **kwargs)

    def __str__(self):
        return "commentaire : %s" % self.content

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {# mdl css #}
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.1/material.red-indigo.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    {# own css #}
    <link rel="stylesheet/less" type="text/css" href="{% static 'css/style.less' %}">
    {% block css %}{% endblock %}
    {# js #}
    <script src="{% static 'js/material.js' %}" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    {% block js_url %}{% endblock %}
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/less.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/dotdot.js' %}" type="text/javascript"></script>

    {# favicon #}
    <link rel="icon" type="image/png" href="/media/favicon-commit.png">

    {# titre #}
    <title>Danzé en LDC</title>
</head>
<body>

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer
            mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <div class="mdl-layout-spacer"></div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
                  mdl-textfield--floating-label mdl-textfield--align-right">
        <label class="mdl-button mdl-js-button mdl-button--icon"
               for="fixed-header-drawer-exp">
          <i class="material-icons">search</i>
        </label>
        <div class="mdl-textfield__expandable-holder">
          <input class="mdl-textfield__input" type="text" name="sample"
                 id="fixed-header-drawer-exp">
        </div>
      </div>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <nav class="mdl-navigation">

        {% if request.user.is_authenticated %}
            <div id="connected_user">
                <p>
                    <i class="material-icons account_icon" role="presentation">account_circle</i> {{ user.username }}
                    <!-- Right aligned menu below button -->
                    <button id="action_profile" class="mdl-button mdl-js-button mdl-button--icon">
                      <i class="material-icons">settings</i>
                    </button>

                    <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="action_profile">
                      <li class="mdl-menu__item"><a href="{% url "change_password" %}">Modifier le mot de passe</a></li>
                      <li disabled class="mdl-menu__item">Ajouter un mail</li>
                    </ul>
                </p>
            </div>
            <p id="drawer_title">Menu</p>
            <a class="mdl-navigation__link {% block accueil_active %}{% endblock %}" href="{% url "get_articles" %}">
                <i class="material-icons" role="presentation">home</i>
                Accueil
            </a>
            <a class="mdl-navigation__link {% block deconnexion_active %}{% endblock %}" href="{% url "logout" %}">
                <i class="material-icons">cancel</i>
                Déconnexion
            </a>

        {% else %}
            <p id="drawer_title">Menu</p>
            <a class="mdl-navigation__link {% block accueil_active_2 %}{% endblock %}" href="{% url "get_articles" %}">
                <i class="material-icons" role="presentation">home</i>
                Accueil
            </a>
            <a class="mdl-navigation__link {% block inscription_active %}{% endblock %}" href="{% url "create_user" %}">
                <i class="material-icons">person_add</i>
                Inscription
            </a>
            <a class="mdl-navigation__link {% block connexion_active %}{% endblock %}" href="{% url "login" %}">
                <i class="material-icons">account_circle</i>
                Connexion
            </a>
        {% endif %}
    </nav>
  </div>


  <main class="mdl-layout__content">
    <div class="page-content">{% block content %}{% endblock %}</div>
  </main>

    {% if perms.articles.add_article %}

        {% block fab_create_article %}
            <a href="{% url "create_article" %}" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect button_fab_action" id="button_add_article">
                <i class="material-icons">add</i>
            </a>

            <div class="mdl-tooltip mdl-tooltip--large mdl-tooltip--left" for="button_add_article">
                Ajouter un article
            </div>
        {% endblock %}
    {% endif %}

    {% block snackbar %}
        {% if messages %}
            {% for msg in messages %}
                <div class="snackbar" id="form_state">
                    <span class="snackbar_text"><i class="material-icons">{{ msg.extra_tags }}</i> {{ msg }}</span>
                    <span class="snackbar_close">Fermer</span>
                </div>
            {% endfor %}
        {% endif %}
    {% endblock %}

</div>

<script>
    $(function snackbarHide(){
        var snackbar = $('.snackbar');
        var leftSnack = $(window).width()*0.5 - snackbar.width()/2;
        snackbar.css('left', leftSnack + 'px');
        snackbar.fadeIn().delay(6000).fadeOut();
        $('.snackbar_close').click(function() {
            snackbar.stop(true, true).fadeOut();
        });
    });

    // supprimer les paragraphes vides
    $('p').each(function() {
        var $this = $(this);
        if($this.html().replace(/\s|&nbsp;/g, '').length == 0)
            $this.remove();
    });
</script>

{# google analytics #}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74093513-1', 'auto');
  ga('send', 'pageview');

</script>

{% block script %}{% endblock %}

</body>
</html>

templates/form.html
{% load widget_tweaks %}

<form action="" method="post">
    {% csrf_token %}

    {% for field in form %}

        <div class="input">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            {{ field|add_class:"mdl-textfield__input" }}
            <label class="mdl-textfield__label" for="{{ field.id_for_label }}">{{ field.label }}</label>
          </div>

          {% if field.errors %}
              {% for error in field.errors %}
                  <p class="form_errors"><i class="material-icons">report_problem</i> {{ error }}</p>
              {% endfor %}
          {% endif %}
        </div>

    {% endfor %}

    <input type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect" value="Envoyer">
</form>

{% block error_form %}{% endblock %}